# Site settings
title: EverySpace Society
email: dausha+espace@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://espacesociety.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - _config.yml
  - _sass
  - _site
  - _data
  - config
  - config.ru
  - vendor

## Site Specific
cdn_url: https://s3.amazonaws.com/dausha