cp -R ../espace/source/_redirects.json .
cp -R ../espace/source/aaron-clausen .
cp -R ../espace/source/astro-empires .
cp -R ../espace/source/astrography .
cp -R ../espace/source/b-os-the-enclave .
cp -R ../espace/source/campaigns .
cp -R ../espace/source/chronology .
cp -R ../espace/source/contributers .
cp -R ../espace/source/contributions .
cp -R ../espace/source/cosmology .
cp -R ../espace/source/current-events .
cp -R ../espace/source/custom .
cp -R ../espace/source/d20rules .
cp -R ../espace/source/epsilon-indi .
cp -R ../espace/source/eve-online .
cp -R ../espace/source/events .
cp -R ../espace/source/fiction-notes .
cp -R ../espace/source/fudge-rules .
cp -R ../espace/source/galactic-loonies .
cp -R ../espace/source/generalities .
cp -R ../espace/source/geography-and-history .
cp -R ../espace/source/index.html .
cp -R ../espace/source/language .
cp -R ../espace/source/literature-and-rhetoric .
cp -R ../espace/source/macrodyn-tectronics .
cp -R ../espace/source/macropedia .
cp -R ../espace/source/main .
cp -R ../espace/source/mechanics .
cp -R ../espace/source/milieu .
cp -R ../espace/source/natural-sciences .
cp -R ../espace/source/philosophy-and-psychology .
cp -R ../espace/source/religion .
cp -R ../espace/source/role-playing .
cp -R ../espace/source/scholar .
cp -R ../espace/source/site .
cp -R ../espace/source/site-admin .
cp -R ../espace/source/social-sciences .
cp -R ../espace/source/space-travel .
cp -R ../espace/source/star-systems .
cp -R ../espace/source/stylesheets .
cp -R ../espace/source/technology .
cp -R ../espace/source/the-arts .
